version: '3'

services:
  php-apache:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:80"
    volumes:
      - ./src/:/var/www/html/
      - ../config/:/var/www/config/
      - ../bin/:/root/bin/
